#!/bin/zsh
eb local setenv RDS_HOSTNAME=$RDS_HOSTNAME
eb local setenv RDS_PORT=$RDS_PORT
eb local setenv RDS_DB_NAME=$RDS_DB_NAME
eb local setenv RDS_USERNAME=$RDS_USERNAME
eb local setenv RDS_PASSWORD=$RDS_PASSWORD
eb local setenv RENTMONITOR_DB_ENCRYPTION_SECRET=$RENTMONITOR_DB_ENCRYPTION_SECRET
eb local setenv RENTMONITOR_DB_ENCRYPTION_SALT=$RENTMONITOR_DB_ENCRYPTION_SALT
eb local setenv RENTMONITOR_JWT_SECRET=$RENTMONITOR_JWT_SECRET
eb local printenv
eb local run
