#!/bin/zsh
eb local setenv RENTMONITOR_DB_HOST=$RENTMONITOR_DB_HOST
eb local setenv RENTMONITOR_DB_PORT=$RENTMONITOR_DB_PORT
eb local setenv RENTMONITOR_DB_USER=$RENTMONITOR_DB_USER
eb local setenv RENTMONITOR_DB_PASSWORD=$RENTMONITOR_DB_PASSWORD
eb local setenv RENTMONITOR_DB_ENCRYPTION_SECRET=$RENTMONITOR_DB_ENCRYPTION_SECRET
eb local setenv RENTMONITOR_DB_ENCRYPTION_SALT=$RENTMONITOR_DB_ENCRYPTION_SALT
eb local setenv RENTMONITOR_JWT_SECRET=$RENTMONITOR_JWT_SECRET
eb local printenv
eb local run
