service: rentmonitor
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  timeout: 900
  environment:
    NODE_ENV: dev
functions:
  app:
    handler: lambda.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
  - serverless-webpack
package:
  patterns:
    - '!amplify/**'
    - '!deploy/**'
    - '!Dockerfile*'
    - '!*.sh'
    - '!src/**'
custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - '@loopback/testlab'
